name: Go build and test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install the xmorph C headers and libraries
        run: |
          sudo apt install -y libmorph-dev
          sudo touch /usr/include/xmorph/braindead_msvc.h
        
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
